### ISSUE TITLE
how to modify 'infos' return from env.step()?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/habitat-lab#502]
I have marked a green dot in the topdownmap (18, 50)　by program, as shown in the following figure:
![image](https://user-images.githubusercontent.com/34536352/96081252-81a35300-0eeb-11eb-913d-7ba0ef633e8a.png)

I checked the content in the infos as follows:
{'distance_to_goal': 6.0, 
'normalized_distance_to_goal': 1.0909090909090908, 
'success': 0.0, 'spl': 0.0, 
'softspl': 0.0,
 'top_down_map': {
'map': array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), 
'fog_of_war_mask': array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), 
'agent_map_coord': (165, 776), 
'agent_angle': 1.5707963267948966
	}
}

```
observation, reward, done, info = env.step(**{'action': action})

```
How do I add a data similar to info["top_down_map"]["agent_map_coord"] in this simulator? In this way, every time the agent takes a step, I can dynamically add points to the infos. My ultimate goal is to add a new green round point similar to "goal" in the top down map.

**Comment by rpartsey** [comment]
@yyf17 if the data you want to add should be a part of `info["top_down_map"]` then you may subclass the [TopDownMap](https://github.com/facebookresearch/habitat-lab/blob/e2cb80843f6ddf24ffd3964976a5136963c03568/habitat/tasks/nav/nav.py#L696) measure, overload `update_metric` and new class instead of TopDownMap measure.

If the data should not be a part of `info["top_down_map"]` then define and register a new measure (have to be a subclass of [Measure](https://github.com/facebookresearch/habitat-lab/blob/e2cb80843f6ddf24ffd3964976a5136963c03568/habitat/core/embodied_task.py#L79)).

For more details on how to define, register and use custom sensors/measures check the [example](https://github.com/facebookresearch/habitat-lab/blob/2acd836485e7db78328be3b4863ca6f4c7239b36/examples/register_new_sensors_and_measures.py#L77).
