### ISSUE TITLE
PPO hyperparameter tuning

### ISSUE THREAD

**Issue by yuyecreus** [facebookresearch/habitat-lab#636]
Hello everybody,

I just wanted to get some intuition about the importance of some PPO parameters. Concretely, I wonder what role do play the following:

LOG INTERVAL = 10
NUM_UPDATES: -1
NUM_ENVIRONMENTS  = 1 (as NUM_SCENES = 1, as I am only testing PPO in one apartment)
NUM_ENVIRONMENTS = 1 implies num_mini_batch = 1 which I don't know if is okay. 

And then I am just using the baseline parameters in "ppo_pointnav.yml":

RL:
  PPO:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 4
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 128 (only difference here as my custom encoder returns embeddings of dim = 128)
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50

Given the constraints of 1 environment and hence 1 mini_batch, does it make sense to use these set of hyperparameters?

Thank you very much guys! :)

**Comment by erikwijmans** [comment]
1 environment will generally perform poorly as that limits the batch size.  You'll get better performance by hacking up https://github.com/facebookresearch/habitat-lab/blob/master/habitat_baselines/utils/env_utils.py#L61-L82 to duplicate scenes.  This will lead to incorrect evaluation if you use more than 1 environment tho (which is why that check is there)
